# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: 2c9f875913ee60ca25ce70243dc24d5b6415598c  # frozen: v4.6.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
        args: [--unsafe]
    -   id: check-json
    -   id: check-xml
    -   id: check-toml
    -   id: check-added-large-files
    -   id: check-ast
    -   id: check-case-conflict
    -   id: check-merge-conflict
    -   id: check-executables-have-shebangs
    -   id: detect-aws-credentials
        args: ["--allow-missing-credentials"]
    -   id: requirements-txt-fixer

- repo: https://github.com/psf/black
  rev: b965c2a5026f8ba399283ba3e01898b012853c79  # frozen: 24.8.0
  hooks:
  - id: black
    args: ["--line-length", "120"]

- repo: https://github.com/Lucas-C/pre-commit-hooks
  rev: a30f0d816e5062a67d87c8de753cfe499672b959  # frozen: v1.5.5
  hooks:
  - id: remove-tabs
    exclude: (Makefile$|\.bat$|\.cmake$|\.eps$|\.fits$|\.opt$)

- repo: https://github.com/pycqa/isort
  rev: c235f5e450b4b84e58d114ed4c589cbf454175a3  # frozen: 5.13.2
  hooks:
  - id: isort
    args: ["--profile", "black"]
    name: isort (python)
